In [2]:
from Bio import Phylo
import pandas as pd

from glob import glob

In [10]:
%cd ../analysis/4.WY_tree

/var2/Works/junhyeong/RXLR_landscape/analysis/4.WY_tree

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [40]:
tree_cluster = {}

In [41]:
for i, hsc in enumerate(sorted(glob("./hSC*.txt"))):
    with open(hsc) as f:
        print(hsc)
        for line in f.readlines():
            tree_cluster[line.strip().replace(" ", "_")] = i+1

./hSC1.txt
./hSC2.txt
./hSC3.txt
./hSC4.txt

In [42]:
df = pd.read_csv("./RXLR_WY.tsv",  sep = "\t")

In [43]:
df["tree_cluster"] = df["entry"].map(tree_cluster)

In [44]:
df_w_cluster = df.sort_values(["tree_cluster", "str_cl", "seq_cl", "entry"])

In [45]:
df_w_cluster

,entry,spp,WY,LWY,type,seq,seq_cl,str_cl,PFam,tree_cluster
15,POM75974,Phypal,2.0,0.0,WY,GFERIIQQPIKLNTPGKIDNILGVKKLDELLDPARADALLAKNKLG...,-1,-1,<UNK>,1.0
23,Phyker_46568.831,Phyker,1.0,0.0,WY,GFSLSGLMDKLAAKKLAKAALEDSSKEVQAYRAWEANGHTLDDIKK...,12,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
35,Phyra78544,Phyram,1.0,0.0,WY,GVITNPIRRDMLSSSAYKKEVFDNWLLHNKSSATIRDYLNLNGKRW...,51,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
47,OWZ00140,Phymeg,1.0,0.0,WY,SIIALTKLKTATKKIFDVILKPFKKADHWFMKRLQNDVFERRYRNG...,257,-1,<UNK>,1.0
46,OWZ08332,Phymeg,1.0,0.0,WY,SIVPLKKLKTATKRIFDAISKQFKKAGHWFMKTLREEHYYKKWYRN...,257,-1,<UNK>,1.0
...,...,...,...,...,...,...,...,...,...,...
1785,Phyci1_2936,Phycin,0.0,0.0,no (L)WY,MFSGALPENIASVAKKLPRSKSLPDLRLTVKGKKAVDRLVAQLTRS...,-1,182,<UNK>,NaN
1786,XP_009532894.1,Physoj,1.0,0.0,WY,GIANNPSVAKVLYKLTPNKQKAAEKLFKRLKLGKNTPSIFTNAKFL...,-1,182,<UNK>,NaN
1787,OWZ15803,Phymeg,1.0,0.0,WY,LDERGLNLGVKLKDLTTSATKTLEKFALSAKINKITNNQLATDKSF...,66,182,<UNK>,NaN
1800,Phyinf1_13649,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN
1801,Phyinf1_13658,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN

In [46]:
df_w_cluster.to_csv("RXLR_tree_cluster_by_manual.tsv", sep = "\t", index = False)

In [47]:
df_w_cluster.groupby("tree_cluster").count()

              entry  spp   WY  LWY  type  seq  seq_cl  str_cl  PFam
tree_cluster
1.0             936  936  936  936   936  936     936     936   936
2.0             624  624  624  624   624  624     624     624   624
3.0             126  126  126  126   126  126     126     126   126
4.0              32   32   32   32    32   32      32      32    32

# etc

In [15]:
df_w_cluster[df_w_cluster["tree_cluster"] == 5].to_csv("../../awr/tree_awr_candidate.tsv", sep = "\t", index = False)