In [1]:
%cd ../analysis/4.WY_tree/

/var2/Works/junhyeong/RXLR_landscape/analysis/4.WY_tree

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [2]:
!ls -al

total 1872
drwxrwxr-x.  4 junhyeong junhyeong   4096 Feb 24 15:52 .
drwxrwxr-x. 13 junhyeong junhyeong   4096 Feb 24 10:17 ..
-rw-rw-r--.  1 junhyeong junhyeong  10832 Jan 28 15:48 hSC1.txt
-rw-rw-r--.  1 junhyeong junhyeong   7235 Jan 28 15:48 hSC2.txt
-rw-rw-r--.  1 junhyeong junhyeong   1486 Jan 28 15:36 hSC3.txt
-rw-rw-r--.  1 junhyeong junhyeong    391 Jan 28 15:36 hSC4.txt
drwxrwxr-x.  2 junhyeong junhyeong   4096 Feb 24 15:52 .ipynb_checkpoints
-rw-rw-r--.  1 junhyeong junhyeong     77 Dec 17 14:30 run_tmalign.log
-rw-rw-r--.  1 junhyeong junhyeong  95694 Dec 17 14:37 RXLR_structure_UPGMA_tree_id_updated.nwk
-rw-rw-r--.  1 junhyeong junhyeong 439696 Dec 17 14:37 RXLR_tree_cluster_by_branch_length.tsv
-rw-rw-r--.  1 junhyeong junhyeong 414459 Jan 28 15:48 RXLR_tree_cluster_by_manual.tsv
-rw-rw-r--.  1 junhyeong junhyeong 341718 Dec 17 10:49 RXLR_WY.fasta
-rw-rw-r--.  1 junhyeong junhyeong  28177 Dec 17 14:20 RXLR_WY.list
-rw-rw-r--.  1 junhyeong junhyeong 407490 Dec 17 10:49 RXLR_WY.tsv
-rw-rw-r--.  1 junhyeong junhyeong  54716 Feb 24 15:52 tree_scores.txt
drwxrwxr-x.  2 junhyeong junhyeong  69632 Dec 17 14:20 wy_pdb

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("RXLR_tree_cluster_by_manual.tsv", sep = "\t")

In [6]:
df

,entry,spp,WY,LWY,type,seq,seq_cl,str_cl,PFam,tree_cluster
0,POM75974,Phypal,2.0,0.0,WY,GFERIIQQPIKLNTPGKIDNILGVKKLDELLDPARADALLAKNKLG...,-1,-1,<UNK>,1.0
1,Phyker_46568.831,Phyker,1.0,0.0,WY,GFSLSGLMDKLAAKKLAKAALEDSSKEVQAYRAWEANGHTLDDIKK...,12,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
2,Phyra78544,Phyram,1.0,0.0,WY,GVITNPIRRDMLSSSAYKKEVFDNWLLHNKSSATIRDYLNLNGKRW...,51,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
3,OWZ00140,Phymeg,1.0,0.0,WY,SIIALTKLKTATKKIFDVILKPFKKADHWFMKRLQNDVFERRYRNG...,257,-1,<UNK>,1.0
4,OWZ08332,Phymeg,1.0,0.0,WY,SIVPLKKLKTATKRIFDAISKQFKKAGHWFMKTLREEHYYKKWYRN...,257,-1,<UNK>,1.0
...,...,...,...,...,...,...,...,...,...,...
1797,Phyci1_2936,Phycin,0.0,0.0,no (L)WY,MFSGALPENIASVAKKLPRSKSLPDLRLTVKGKKAVDRLVAQLTRS...,-1,182,<UNK>,NaN
1798,XP_009532894.1,Physoj,1.0,0.0,WY,GIANNPSVAKVLYKLTPNKQKAAEKLFKRLKLGKNTPSIFTNAKFL...,-1,182,<UNK>,NaN
1799,OWZ15803,Phymeg,1.0,0.0,WY,LDERGLNLGVKLKDLTTSATKTLEKFALSAKINKITNNQLATDKSF...,66,182,<UNK>,NaN
1800,Phyinf1_13649,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN
1801,Phyinf1_13658,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN

In [9]:
exp = pd.read_csv("../../data/Experimentally_validated_RXLR_effectors.tsv", sep = "\t")

In [10]:
exp

,Gene name,Uniprot entry,Gene ID used in this study,Species,Uniprot entry.1,Sequences
0,RxL17,RxL17,Hyaar1_11942,H. arabidopsidis,M4BMH6,MQSILWFALIASVVFLVLVDLASGLNGLETLSSGADVDELTTATRL...
1,HaATR1,Hyaar1_13760,Hyaar1_13760,H. arabidopsidis,M4B6G6,MRVCYFVLVPSVALAVIATESSETSGTIVHVFPLRDVADHRNDALI...
2,Avirulence protein ATR39-2 (Arabidopsis thalia...,ATR39-2,Hyaar1_1630,H. arabidopsidis,M4BUU2,MVKCTPLLALTVIVSAGSDALSDPTVKRLAKLATINQAPATQSNSD...
3,RxL62,RxL62,Hyaar1_7062,H. arabidopsidis,M4C319,MRLDILLFTLSSSTSLALSYSLPMDPAHSSVHTLSAADRHIGERVT...
4,Virulence protein ATR13 (Arabidopsis thaliana ...,ATR13,Hyaar1_7110,H. arabidopsidis,M4C367,MRLVHAVLLPGIIVFVSNGNLLHAHALHEDETGVTAGRQLRAAASE...
...,...,...,...,...,...,...
94,PsAvh52,XP_009531469.1,XP_009531469.1,P. sojae,G1FR37,MRLTSILVLVIAATFHTTGTALTLTKDSKAGIANGDSPASGDFIDA...
95,PsAvh262,XP_009535769.1,XP_009535769.1,P. sojae,NaN,MLPVAVVLVVFAVAVTSAESIHQVNPLPRRRRLKGTEEKGHHTNVN...
96,Avh241 (Avirulence homolog protein 241),Avh241 PHYSODRAFT_288810,XP_009536330.1,P. sojae,G5A8D2,MRQYCLLLIVLALAAALSDNAVASTLAVARSEIGAPSAVYSERLLR...
97,Avh240 (Avirulence homolog protein 2402),Avh240 PHYSODRAFT_288823,XP_009536419.1,P. sojae,G5A8M1,MRPYFTLLLALAFILACTNLVEADAGRVLETTTNEHARHLRTAVAS...
98,PsPSR2,XP_009538063.1,XP_009538063.1,P. sojae,"E0W4V5, G5ADB3",MRLQCVVLFAALTLVAATHAPPNVKTVLSAEQHDIPVKRLLRPGNP...

In [12]:
merged = pd.merge(exp, df, left_on = "Gene ID used in this study", right_on = "entry", how = "left")

In [14]:
merged.to_csv("Exp_val_hSCs.txt", sep = "\t", index = False)