In [2]:
import pandas as pd
from Bio import SeqIO

# Predicted RXLR effectors

In [3]:
predicted_rxlr_effectors = pd.read_csv("../analysis/1.RXLR_prediction/1-2.pattern_match/Predicted_RXLR_effectors.tsv", sep = "\t")

In [4]:
predicted_rxlr_effectors

,entry,seq,spp,type,EER,effector_domain,RXLR motif,EER motif
0,Phyca11_503811,CISLSSAANAPTTSNGVRRLRLAVDVQEERGIADVLSGAITSMKAK...,Phycap,RXLR,True,GIADVLSGAITSMKAKVTTNSGKIVEGLKTTAQLSDDQAAKMAKIF...,RRLR,EER
1,Phyca11_5186,CNATAVSDQGKTPTVHSLDARLNDDTGDRRSLRAFKEKEEFDTEER...,Phycap,RXLR,True,DPSKADDAYKTWADKGYTLSQLSGFLTSKTKGKYDRVYNGYAIHLDY,RSLR,EER
2,Phyca11_130393,ETHITSNVQLHSEDIVRRLRFAPEQVEERGLTVPKFQDIVNNQQLA...,Phycap,RXLR,True,GLTVPKFQDIVNNQQLAWWLKRGKTTDDVFAKLKLNLAGSSIFENP...,RRLR,EER
3,Phyca11_109432,DPASVAAVHSSRVLSDEDKRFLRRHPTEHDNEERAFGQNMFAALKL...,Phycap,RXLR,True,AFGQNMFAALKLSKMKTDAEYRVKVFHRWKKHGYTADDVAKHVPAK...,RFLR,EER
4,Phyca11_129643,VNPTHDERLLRTSTSTKTSTSETEERAIDAAMIARLNDEWQAAVMR...,Phycap,RXLR,True,AIDAAMIARLNDEWQAAVMRAAYAHWFEGGKTKADVRLIMSLPPTG...,RLLR,EER
...,...,...,...,...,...,...,...,...
4320,Phyker_46568.2573,ALRSSSSSSMPEIELDYSTIRAVAANETVGYYKYQNIRFAAVPTGD...,Phyker,RXLR,NaN,FAAPEFPPQETETNTGTNLADADVDCSSTEDCLYLDVWAPANATNL...,GDLR,NaN
4321,Phyker_46568.713,DSPADARALNVVSNERGAKRSLRTMNEESNEVDSTDEADGTEEEDR...,Phyker,RXLR,True,ILFMGRLKNKWDLRSMRKAADKDFKKQAKELEKLDKAAKKQQKQID...,RSLR,EDR
4322,Phyker_46568.8989,GSSTATTAKPEEVYAAVFRVKDGKVTDAMLKDINQNDGSVYYLNQD...,Phyker,RXLR,NaN,IEA,RRLR,NaN
4323,Phyker_46568.8775,IHLTTVAWNEDKELLCHAHNKGVKVVVKHNFDDVEQLCNATARRDW...,Phyker,RXLR,NaN,RELELHPLTRNSQITFDVPWAPRGVDGRYYPWRELAGAVDFLFVMS...,QELR,NaN
4324,Phyker_46568.7290,APQPRNLRQNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVS...,Phyker,RXLR,NaN,QNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVSAHRVYDPV...,RNLR,NaN

In [47]:
predicted_rxlr_effectors["effector_domain"].fillna("", inplace = True)

In [48]:
predicted_rxlr_effectors["len"] = predicted_rxlr_effectors["effector_domain"].apply(len)

In [49]:
predicted_rxlr_effectors

,entry,seq,spp,type,EER,effector_domain,RXLR motif,EER motif,len
0,Phyca11_503811,CISLSSAANAPTTSNGVRRLRLAVDVQEERGIADVLSGAITSMKAK...,Phycap,RXLR,True,GIADVLSGAITSMKAKVTTNSGKIVEGLKTTAQLSDDQAAKMAKIF...,RRLR,EER,249
1,Phyca11_5186,CNATAVSDQGKTPTVHSLDARLNDDTGDRRSLRAFKEKEEFDTEER...,Phycap,RXLR,True,DPSKADDAYKTWADKGYTLSQLSGFLTSKTKGKYDRVYNGYAIHLDY,RSLR,EER,47
2,Phyca11_130393,ETHITSNVQLHSEDIVRRLRFAPEQVEERGLTVPKFQDIVNNQQLA...,Phycap,RXLR,True,GLTVPKFQDIVNNQQLAWWLKRGKTTDDVFAKLKLNLAGSSIFENP...,RRLR,EER,428
3,Phyca11_109432,DPASVAAVHSSRVLSDEDKRFLRRHPTEHDNEERAFGQNMFAALKL...,Phycap,RXLR,True,AFGQNMFAALKLSKMKTDAEYRVKVFHRWKKHGYTADDVAKHVPAK...,RFLR,EER,74
4,Phyca11_129643,VNPTHDERLLRTSTSTKTSTSETEERAIDAAMIARLNDEWQAAVMR...,Phycap,RXLR,True,AIDAAMIARLNDEWQAAVMRAAYAHWFEGGKTKADVRLIMSLPPTG...,RLLR,EER,135
...,...,...,...,...,...,...,...,...,...
4320,Phyker_46568.2573,ALRSSSSSSMPEIELDYSTIRAVAANETVGYYKYQNIRFAAVPTGD...,Phyker,RXLR,NaN,FAAPEFPPQETETNTGTNLADADVDCSSTEDCLYLDVWAPANATNL...,GDLR,NaN,699
4321,Phyker_46568.713,DSPADARALNVVSNERGAKRSLRTMNEESNEVDSTDEADGTEEEDR...,Phyker,RXLR,True,ILFMGRLKNKWDLRSMRKAADKDFKKQAKELEKLDKAAKKQQKQID...,RSLR,EDR,100
4322,Phyker_46568.8989,GSSTATTAKPEEVYAAVFRVKDGKVTDAMLKDINQNDGSVYYLNQD...,Phyker,RXLR,NaN,IEA,RRLR,NaN,3
4323,Phyker_46568.8775,IHLTTVAWNEDKELLCHAHNKGVKVVVKHNFDDVEQLCNATARRDW...,Phyker,RXLR,NaN,RELELHPLTRNSQITFDVPWAPRGVDGRYYPWRELAGAVDFLFVMS...,QELR,NaN,224
4324,Phyker_46568.7290,APQPRNLRQNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVS...,Phyker,RXLR,NaN,QNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVSAHRVYDPV...,RNLR,NaN,170

In [50]:
predicted_rxlr_effectors["bin"] = (predicted_rxlr_effectors["len"] // 10) * 10

In [54]:
predicted_rxlr_effectors.groupby("bin").size().to_csv("../analysis/length_bin.tsv", sep = "\t")

In [51]:
predicted_rxlr_effectors.groupby("spp").count()

,entry,seq,type,EER,effector_domain,RXLR motif,EER motif,len,bin
spp,,,,,,,,,
Brelac,117,117,117,41,117,117,41,117,117
Hyaara,111,111,111,38,111,111,38,111,111
Phycac,316,316,316,162,316,316,162,316,316
Phycap,172,172,172,109,172,172,109,172,172
Phycin,297,297,297,159,297,297,159,297,297
Phyinf,524,524,524,369,524,524,369,524,524
Phyker,104,104,104,45,104,104,45,104,104
Phylat,117,117,117,51,117,117,51,117,117
Phymeg,845,845,845,696,845,845,696,845,845
Phypal,548,548,548,441,548,548,441,548,548
Phypar,391,391,391,244,391,391,244,391,391
Phyram,195,195,195,109,195,195,109,195,195
Physoj,430,430,430,244,430,430,244,430,430
Pytaph,81,81,81,5,81,81,5,81,81
Pytult,77,77,77,4,77,77,4,77,77

# WY domain prediction

## WY domain, species

In [6]:
predicted_wy_domains = pd.read_csv("../analysis/3.Clustering/3-1.domain_prediction/Predicted_WY_annotation_in_RXLR_effectors.tsv", sep = "\t")

In [39]:
wy_annotation = pd.crosstab(index=predicted_wy_domains["spp"], columns = predicted_wy_domains["type"])

In [41]:
wy_annotation.to_csv("../analysis/wy_annotation.tsv", sep = "\t")

# clustering and WY domain

In [20]:
clustering_rxlr_effectors = pd.read_csv("../analysis/3.Clustering/3-2.clustering/RXLR_cluster_domain.tsv", sep = "\t")

In [21]:
clustering_rxlr_effectors

,entry,seq,spp,seq_cl,str_cl
0,TDH65555.1,YGWRYPLRYWNRFGRPLFGSNCRFGRPWVGQLDVARCDDEKKEAEK...,Brelac,-1,-1
1,TDH65737.1,YGWRYPLRYWNRKKERGEKEAFDVMTSSFMHIE,Brelac,-1,-1
2,TDH66220.1,NPGIRHSMAWAFSEPINTVLRLKGITAEEAEAKLRAGKFYRKFLYG...,Brelac,-1,-1
3,TDH66451.1,CIGWKATSNCTPDGFRVPGLDFPCNTVVPYGSSGYCEVTDKDTGES...,Brelac,-1,-1
4,TDH66483.1,SLAGALASSLFGSSRSPQTVQSVDFQALLEPSPRLSNYDIKQRLRA...,Brelac,-1,-1
...,...,...,...,...,...
3956,OWY92363,MPGGFYPTFIWKKKWEEHKKKLRRRSRSHKKRSSRTRAN,Phymeg,244,330
3957,OWZ11298,NFDKFSKTHQKHLIRFAKNLGFDLKKSLTDTSYFAGISPDTIHKYH...,Phymeg,54,331
3958,OWZ06367,GKGFFDFSREHQKQLKDFAKDLGFNLKAALKDPRVFNRIDEEAWEK...,Phymeg,54,331
3959,OWZ05828,HFGNADDERKLRSDYSGYEEERHFGEP,Phymeg,396,332
3960,OWY97922,HFGNADDERKLRSDYSGYEEERHFGEP,Phymeg,396,332

In [8]:
predicted_wy_domains

                  entry     spp   WY  LWY      type
0        Phyca11_503811  Phycap  0.0  0.0  no (L)WY
1          Phyca11_5186  Phycap  0.0  0.0  no (L)WY
2        Phyca11_130393  Phycap  5.0  5.0       LWY
3        Phyca11_109432  Phycap  2.0  0.0        WY
4        Phyca11_129643  Phycap  2.0  0.0        WY
...                 ...     ...  ...  ...       ...
4320  Phyker_46568.2573  Phyker  0.0  0.0  no (L)WY
4321   Phyker_46568.713  Phyker  1.0  0.0        WY
4322  Phyker_46568.8989  Phyker  0.0  0.0  no (L)WY
4323  Phyker_46568.8775  Phyker  0.0  0.0  no (L)WY
4324  Phyker_46568.7290  Phyker  0.0  0.0  no (L)WY

[4325 rows x 5 columns]

In [24]:
df = pd.merge(predicted_wy_domains, clustering_rxlr_effectors, on = ["entry", "spp"], how = "right")

In [30]:
wy_containing_cluster = set(cluster for cluster in df[df["type"] != "no (L)WY"]["str_cl"])

In [34]:
len(wy_containing_cluster) - 1 # discard singleton

80

In [36]:
df[df["str_cl"].map(lambda x: x in wy_containing_cluster and x != -1)].groupby("type").count()

          entry  spp   WY  LWY  seq  seq_cl  str_cl
type
LWY         521  521  521  521  521     521     521
WY          595  595  595  595  595     595     595
no (L)WY    647  647  647  647  647     647     647

In [38]:
df[df["str_cl"].map(lambda x: x in wy_containing_cluster and x != -1)].to_csv("../analysis/3.Clustering/WY_containing_cluster_entries.tsv", sep = "\t", index = False)

# structure prediction

In [55]:
prediction_scores = pd.read_csv("../analysis/2.Structure_prediction/RXLR_fasta_v3.tsv", sep = "\t")

In [56]:
prediction_scores

,entry,seq,plddt,ptm
0,TDH64719.1,VAMTTDVVMHGGIVGKLKELLPNNDISNPFSKTRPSKTVTNSYGFN...,33.366736,0.24
1,TDH64798.1,ELFLKRSNVPFSIREAYNRNLQEHMTYLEDVNMYARQVRHEFSYDM...,88.604146,0.82
2,TDH65555.1,YGWRYPLRYWNRFGRPLFGSNCRFGRPWVGQLDVARCDDEKKEAEK...,67.174348,0.35
3,TDH65737.1,YGWRYPLRYWNRKKERGEKEAFDVMTSSFMHIE,80.266667,0.37
4,TDH65748.1,NKGFIYTLNKLHVWNMLEYERVVYLDADNILIRNSDELFLCGEFCA...,76.312921,0.69
...,...,...,...,...
4133,PYU1_T007635,KDGTVDLVIELAQTTESTLESIQETAFSSRTAKVEAIKSKLQAQSK...,95.434218,0.95
4134,PYU1_T002439,SDSGSGSVHEDENKTATHIFKSASDVKVGPGIVAAGAIVVGLVVCL...,76.487947,0.66
4135,PYU1_T003553,QQGFVNLIVILADTTESTLESIQESEYATRTDRINALKSKLEAGNK...,96.082014,0.95
4136,PYU1_T003569,VQGNYGGGGGATQSTGGASMSAGASGGAYDSSSGKTSSSGVKSSSS...,41.648927,0.12
4137,PYU1_T008793,GDVNCGAPPQVYQGTASYSSTKAGATVRYSCIRGCVMRGSATATCT...,82.587317,0.66

In [60]:
prediction_scores["plddt_bin"] = (prediction_scores["plddt"] // 10) * 10

In [61]:
prediction_scores["ptm_bin"] = (prediction_scores["ptm"] // 10) * 10

In [62]:
prediction_scores

,entry,seq,plddt,ptm,plddt_bin,ptm_bin
0,TDH64719.1,VAMTTDVVMHGGIVGKLKELLPNNDISNPFSKTRPSKTVTNSYGFN...,33.366736,0.24,30.0,0.0
1,TDH64798.1,ELFLKRSNVPFSIREAYNRNLQEHMTYLEDVNMYARQVRHEFSYDM...,88.604146,0.82,80.0,0.0
2,TDH65555.1,YGWRYPLRYWNRFGRPLFGSNCRFGRPWVGQLDVARCDDEKKEAEK...,67.174348,0.35,60.0,0.0
3,TDH65737.1,YGWRYPLRYWNRKKERGEKEAFDVMTSSFMHIE,80.266667,0.37,80.0,0.0
4,TDH65748.1,NKGFIYTLNKLHVWNMLEYERVVYLDADNILIRNSDELFLCGEFCA...,76.312921,0.69,70.0,0.0
...,...,...,...,...,...,...
4133,PYU1_T007635,KDGTVDLVIELAQTTESTLESIQETAFSSRTAKVEAIKSKLQAQSK...,95.434218,0.95,90.0,0.0
4134,PYU1_T002439,SDSGSGSVHEDENKTATHIFKSASDVKVGPGIVAAGAIVVGLVVCL...,76.487947,0.66,70.0,0.0
4135,PYU1_T003553,QQGFVNLIVILADTTESTLESIQESEYATRTDRINALKSKLEAGNK...,96.082014,0.95,90.0,0.0
4136,PYU1_T003569,VQGNYGGGGGATQSTGGASMSAGASGGAYDSSSGKTSSSGVKSSSS...,41.648927,0.12,40.0,0.0
4137,PYU1_T008793,GDVNCGAPPQVYQGTASYSSTKAGATVRYSCIRGCVMRGSATATCT...,82.587317,0.66,80.0,0.0

In [63]:
prediction_scores.groupby("plddt_bin").size()

plddt_bin
30.0      33
40.0     144
50.0     329
60.0     692
70.0     925
80.0    1191
90.0     824
dtype: int64

In [ ]:
prediction_scores.groupby("plddt_bin").size()

# AWR

In [3]:
!ls -al

total 492
drwxrwxr-x. 3 junhyeong junhyeong   4096 Jan 29 19:42 .
drwxrwxr-x. 7 junhyeong junhyeong   4096 Dec 17 14:38 ..
-rw-rw-r--. 1 junhyeong junhyeong   3829 Dec 16 14:22 1-1.signalp.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  26272 Dec 16 16:07 1-2.pattern_match.ipynb
-rw-rw-r--. 1 junhyeong junhyeong   2609 Dec 16 16:40 1-3.drop_outlier.ipynb
-rw-rw-r--. 1 junhyeong junhyeong   9815 Dec 16 17:23 2-1.qc.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  94157 Dec 16 19:51 3-1.domain.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  10818 Dec 16 20:50 3-2.cluster.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  22506 Dec 17 14:21 4-1.WY_select.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  11108 Dec 17 14:32 4-2.upgma.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  16667 Jan 28 15:49 4-3.cluster_by_branch_length.ipynb
-rw-rw-r--. 1 junhyeong junhyeong 129037 Jan 28 22:30 5-1.awr.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  18738 Jan 29 17:33 5-2.awr_select.ipynb
-rw-rw-r--. 1 junhyeong junhyeong  92235 Jan 29 19:42 analysis.ipynb
drwxrwxr-x. 2 junhyeong junhyeong   4096 Jan 28 14:58 .ipynb_checkpoints
-rw-rw-r--. 1 junhyeong junhyeong  30528 Jan 28 17:08 itols.ipynb

In [4]:
%cd ../analysis/7.AWR-others/

/var2/Works/junhyeong/RXLR_landscape/analysis/7.AWR-others

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [7]:
df = pd.read_csv("./AWR.txt", sep = "\t")

In [8]:
df

,ID,Species,The number of predicted WY1 domain,The number of predicted WY2 domain,The domain arrangements,Note,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Hyaar1_6672,Hyaloperonospora arabidopsidis,2,1,wy1-wy2-wy1,NaN,NaN,NaN,NaN,NaN,NaN
1,OWY90163,P. megakarya,2,1,wy1-wy2-wy1,NaN,NaN,NaN,NaN,NaN,NaN
2,OWY90788,P. megakarya,1,1,wy1-wy2,NaN,NaN,NaN,NaN,NaN,NaN
3,OWY91070,P. megakarya,1,0,wy1,NaN,NaN,NaN,NaN,NaN,NaN
4,OWY91300,P. megakarya,1,1,wy1-wy2,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
266,XP_009532353.1,P. sojae,1,1,wy1-wy2,NaN,NaN,NaN,NaN,NaN,NaN
267,XP_009533941.1,P. sojae,1,1,wy1-wy2,NaN,NaN,NaN,NaN,NaN,NaN
268,XP_009535474.1,P. sojae,1,0,wy1,NaN,NaN,NaN,NaN,NaN,NaN
269,XP_009536330.1,P. sojae,1,0,wy1,NaN,NaN,NaN,NaN,NaN,NaN
270,XP_009537211.1,P. sojae,2,1,wy1-wy2-wy1,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.dropna(axis = 1).groupby("The domain arrangements").count()

,ID,Species,The number of predicted WY1 domain,The number of predicted WY2 domain
The domain arrangements,,,,
wy1,51,51,51,51
wy1-wy1,7,7,7,7
wy1-wy1-wy1,1,1,1,1
wy1-wy1-wy1-wy1,1,1,1,1
wy1-wy1-wy1-wy1-wy1,1,1,1,1
wy1-wy1-wy1-wy1-wy1-wy1,1,1,1,1
wy1-wy1-wy1-wy1-wy1-wy2-wy1,2,2,2,2
wy1-wy1-wy1-wy1-wy2-wy1,6,6,6,6
wy1-wy1-wy1-wy2,2,2,2,2
wy1-wy1-wy1-wy2-wy1,5,5,5,5
wy1-wy1-wy2-wy1,5,5,5,5
wy1-wy2,114,114,114,114
wy1-wy2-wy1,39,39,39,39
wy1-wy2-wy1-wy2,1,1,1,1
wy1-wy2-wy1-wy2-wy1,6,6,6,6
wy2,19,19,19,19
wy2-wy1,9,9,9,9
wy2-wy1-wy2,1,1,1,1

In [10]:
awr = df.dropna(axis = 1)

In [11]:
awr

,ID,Species,The number of predicted WY1 domain,The number of predicted WY2 domain,The domain arrangements
0,Hyaar1_6672,Hyaloperonospora arabidopsidis,2,1,wy1-wy2-wy1
1,OWY90163,P. megakarya,2,1,wy1-wy2-wy1
2,OWY90788,P. megakarya,1,1,wy1-wy2
3,OWY91070,P. megakarya,1,0,wy1
4,OWY91300,P. megakarya,1,1,wy1-wy2
...,...,...,...,...,...
266,XP_009532353.1,P. sojae,1,1,wy1-wy2
267,XP_009533941.1,P. sojae,1,1,wy1-wy2
268,XP_009535474.1,P. sojae,1,0,wy1
269,XP_009536330.1,P. sojae,1,0,wy1
270,XP_009537211.1,P. sojae,2,1,wy1-wy2-wy1

In [31]:
seq_db = {record.id: str(record.seq) for record in SeqIO.parse("./all_protein.faa", "fasta")}

In [32]:
wy1_wy2 = awr[awr["The domain arrangements"] == "wy1-wy2"]

In [33]:
with open("wy1-wy2.fasta", "w") as f:
    for entry in wy1_wy2["ID"]:
        
        f.write(f">{entry}\n{seq_db[entry]}\n")

In [34]:
wy1_wy2_wy1 = awr[awr["The domain arrangements"] == "wy1-wy2-wy1"]

In [35]:
with open("wy1-wy2-wy1.fasta", "w") as f:
    for entry in wy1_wy2_wy1["ID"]:
        
        f.write(f">{entry}\n{seq_db[entry]}\n")

In [36]:
wy1 = awr[awr["The domain arrangements"] == "wy1"]

In [37]:
with open("wy1.fasta", "w") as f:
    for entry in wy1["ID"]:
        
        f.write(f">{entry}\n{seq_db[entry]}\n")

In [38]:
wy2 = awr[awr["The domain arrangements"] == "wy2"]

In [39]:
with open("wy2.fasta", "w") as f:
    for entry in wy2["ID"]:
        
        f.write(f">{entry}\n{seq_db[entry]}\n")

In [40]:
wy1_wy2_wy1_wy2_wy1 = awr[awr["The domain arrangements"] == "wy1-wy2-wy1-wy2-wy1"]

In [41]:
with open("wy1-wy2-wy1-wy2-wy1.fasta", "w") as f:
    for entry in wy1_wy2_wy1_wy2_wy1 ["ID"]:
        
        f.write(f">{entry}\n{seq_db[entry]}\n")

# hmmsearch

In [42]:
!conda run -n homology-env mafft --thread 72 --maxiterate 1000 --quiet --globalpair wy1.fasta > wy1.align.fasta

In [43]:
!conda run -n homology-env hmmsearch -o wy1_vs_wy1.results ../5.AWR/wy1.final.hmm ./wy1.fasta
!conda run -n homology-env hmmsearch -o wy1_vs_wy2.results ../5.AWR/wy2.final.hmm ./wy1.fasta

In [44]:
!conda run -n homology-env mafft --thread 72 --maxiterate 1000 --quiet --globalpair wy1-wy2-wy1.fasta > wy1-wy2-wy1.align.fasta

In [ ]:
!conda run -n homology-env hmmsearch -o wy1-wy2-wy1_vs_wy1.results ../5.AWR/wy1.final.hmm ./wy1-wy2-wy1.fasta
!conda run -n homology-env hmmsearch -o wy1-wy2-wy1_vs_wy2.results ../5.AWR/wy2.final.hmm ./wy1-wy2-wy1.fasta

# Foldmason

In [7]:
import pandas as pd
import shutil
from Bio import SeqIO
import os

In [2]:
%cd ../analysis/7.AWR-others

/var2/Works/junhyeong/RXLR_landscape/analysis/7.AWR-others

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [3]:
!mkdir pdb

In [4]:
!mkdir pdb/wy1-wy2-wy1 pdb/wy1-wy2-wy1-wy2-wy1 pdb/wy1-wy2

In [8]:
arrange = "wy1-wy2"
for record in SeqIO.parse(f"{arrange}.fasta", "fasta"):
    entry = record.id
    seq = record.seq

    if os.path.exists(f"../2.Structure_prediction/pdb_qc/{entry}.pdb"):
        shutil.copyfile(f"../2.Structure_prediction/pdb_qc/{entry}.pdb", f"pdb/{arrange}/{entry}.pdb")

In [9]:
arrange = "wy1-wy2-wy1"
for record in SeqIO.parse(f"{arrange}.fasta", "fasta"):
    entry = record.id
    seq = record.seq

    if os.path.exists(f"../2.Structure_prediction/pdb_qc/{entry}.pdb"):
        shutil.copyfile(f"../2.Structure_prediction/pdb_qc/{entry}.pdb", f"pdb/{arrange}/{entry}.pdb")

In [10]:
arrange = "wy1-wy2-wy1-wy2-wy1"
for record in SeqIO.parse(f"{arrange}.fasta", "fasta"):
    entry = record.id
    seq = record.seq

    if os.path.exists(f"../2.Structure_prediction/pdb_qc/{entry}.pdb"):
        shutil.copyfile(f"../2.Structure_prediction/pdb_qc/{entry}.pdb", f"pdb/{arrange}/{entry}.pdb")

# Cluster, functional domoain, WY domain

In [11]:
import pandas as pd

In [12]:
!pwd

/var2/Works/junhyeong/RXLR_landscape/analysis/7.AWR-others

In [13]:
pfam = pd.read_csv("../3.Clustering/3-1.domain_prediction/Predicted_Pfam_annotation_in_RXLR_effectors.tsv", sep = "\t")

In [14]:
wy = pd.read_csv("../3.Clustering/3-1.domain_prediction/Predicted_WY_annotation_in_RXLR_effectors.tsv", sep = "\t")

In [15]:
cluster = pd.read_csv("../3.Clustering/3-2.clustering/RXLR_cluster_domain.tsv", sep = "\t")

In [19]:
pd.merge([pfam, wy, cluster], how = "inner", on = "entry")

TypeError: merge() missing 1 required positional argument: 'right'

In [24]:
tmp = pd.merge(pfam, wy, how = "inner", on = ["entry", "spp"])

In [28]:
total = pd.merge(tmp, cluster, how = "inner", on = ["entry", "spp"])

In [32]:
total.sort_values(["str_cl", "seq_cl", "spp"]).to_csv("total.tsv", sep = "\t", index = False)

In [50]:
total[["str_cl", "PFam"]].drop_duplicates().fillna("").groupby("str_cl", as_index = False).agg(["count", lambda x: '/'.join(x)]).to_csv("../3.Clustering/cluster_purity.tsv", sep = "\t", index = False)

In [48]:
total[["str_cl", "PFam"]].drop_duplicates()

      str_cl                                               PFam
0         62                                                NaN
1        230  RXLR phytopathogen effector protein, Avirulenc...
2          7                                                NaN
3          4  RXLR phytopathogen effector protein, Avirulenc...
4         13                                                NaN
...      ...                                                ...
3939      -1  ABC-2 type transporter/ABC transporter/ABC tra...
3941      -1                    Papain family cysteine protease
3944      24          LysM domain/Ctr copper transporter family
3950     199                                                NaN
3951      -1            Putative transposase DNA-binding domain

[536 rows x 2 columns]

In [54]:
total[total["str_cl"] != -1].pivot_table(index = "str_cl", columns = "seq_cl", aggfunc = "size", fill_value = 0)

seq_cl,-1,1,2,3,4,5,6,7,8,9,...,411,413,415,416,417,418,419,421,422,423
str_cl,,,,,,,,,,,,,,,,,,,,,
1,1,87,0,16,6,21,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,23,0,19,44,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,1,0,62,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
330,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
331,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
332,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
tmp = total[(total["str_cl"] != -1) & (total["str_cl"] <= 30)]

In [101]:
tmp2 = tmp[tmp["seq_cl"] <= 50]

In [102]:
tmp2.pivot_table(index = "str_cl", columns = "seq_cl", aggfunc = "size", fill_value = 0).to_csv("../3.Clustering/heatmap.txt", sep = "\t")

# data

In [80]:
%cd ../3.Clustering/

/var2/Works/junhyeong/RXLR_landscape/analysis/3.Clustering

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [76]:
domains = []
for idx in total.index:
    pfam = total.loc[idx, "PFam"]
    t = total.loc[idx, "type"]

    if t == "LWY":
        domain = "LWY"
    elif t == "WY":
        domain = "WY"
    else:
        domain = pfam

    domains.append(domain)

total["domain"] = domains

In [81]:
total.sort_values(["str_cl", "seq_cl", "spp"]).to_csv("total.tsv", sep = "\t", index = False)

In [67]:
total.groupby("str_cl").count()

        entry  spp  PFam   WY  LWY  type  seq  seq_cl
str_cl
-1        957  957   118  957  957   957  957     957
 1        195  195     1  195  195   195  195     195
 2        105  105     0  105  105   105  105     105
 3        101  101    13  101  101   101  101     101
 4         95   95    40   95   95    95   95      95
...       ...  ...   ...  ...  ...   ...  ...     ...
 328        2    2     0    2    2     2    2       2
 329        2    2     0    2    2     2    2       2
 330        2    2     0    2    2     2    2       2
 331        2    2     0    2    2     2    2       2
 332        2    2     0    2    2     2    2       2

[333 rows x 8 columns]

In [71]:
total.dropna(subset = "PFam").groupby("str_cl").count()

        entry  spp  PFam   WY  LWY  type  seq  seq_cl
str_cl
-1        118  118   118  118  118   118  118     118
 1          1    1     1    1    1     1    1       1
 3         13   13    13   13   13    13   13      13
 4         40   40    40   40   40    40   40      40
 6         33   33    33   33   33    33   33      33
...       ...  ...   ...  ...  ...   ...  ...     ...
 309        2    2     2    2    2     2    2       2
 310        1    1     1    1    1     1    1       1
 313        2    2     2    2    2     2    2       2
 320        1    1     1    1    1     1    1       1
 324        2    2     2    2    2     2    2       2

[110 rows x 8 columns]

# hSC3 pLDDT pTM

In [83]:
!ls -al

total 1380
drwxrwxr-x.  5 junhyeong junhyeong   4096 Feb 24 13:14 .
drwxrwxr-x. 13 junhyeong junhyeong   4096 Feb 24 10:17 ..
drwxrwxr-x.  5 junhyeong junhyeong   4096 Dec 17 10:36 3-1.domain_prediction
drwxrwxr-x.  5 junhyeong junhyeong   4096 Dec 16 20:50 3-2.clustering
-rw-rw-r--.  1 junhyeong junhyeong  13438 Feb 24 10:42 cluster_purity.tsv
-rw-rw-r--.  1 junhyeong junhyeong   1758 Feb 24 13:14 heatmap.txt
drwxrwxr-x.  2 junhyeong junhyeong   4096 Feb 24 13:14 .ipynb_checkpoints
-rw-rw-r--.  1 junhyeong junhyeong 979436 Feb 24 13:33 total.tsv
-rw-rw-r--.  1 junhyeong junhyeong 386380 Jan 20 16:44 WY_containing_cluster_entries.tsv

In [84]:
%cd ../4.WY_tree/

/var2/Works/junhyeong/RXLR_landscape/analysis/4.WY_tree

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [85]:
df = pd.read_csv("RXLR_tree_cluster_by_manual.tsv", sep = "\t")

In [86]:
df

,entry,spp,WY,LWY,type,seq,seq_cl,str_cl,PFam,tree_cluster
0,POM75974,Phypal,2.0,0.0,WY,GFERIIQQPIKLNTPGKIDNILGVKKLDELLDPARADALLAKNKLG...,-1,-1,<UNK>,1.0
1,Phyker_46568.831,Phyker,1.0,0.0,WY,GFSLSGLMDKLAAKKLAKAALEDSSKEVQAYRAWEANGHTLDDIKK...,12,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
2,Phyra78544,Phyram,1.0,0.0,WY,GVITNPIRRDMLSSSAYKKEVFDNWLLHNKSSATIRDYLNLNGKRW...,51,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
3,OWZ00140,Phymeg,1.0,0.0,WY,SIIALTKLKTATKKIFDVILKPFKKADHWFMKRLQNDVFERRYRNG...,257,-1,<UNK>,1.0
4,OWZ08332,Phymeg,1.0,0.0,WY,SIVPLKKLKTATKRIFDAISKQFKKAGHWFMKTLREEHYYKKWYRN...,257,-1,<UNK>,1.0
...,...,...,...,...,...,...,...,...,...,...
1797,Phyci1_2936,Phycin,0.0,0.0,no (L)WY,MFSGALPENIASVAKKLPRSKSLPDLRLTVKGKKAVDRLVAQLTRS...,-1,182,<UNK>,NaN
1798,XP_009532894.1,Physoj,1.0,0.0,WY,GIANNPSVAKVLYKLTPNKQKAAEKLFKRLKLGKNTPSIFTNAKFL...,-1,182,<UNK>,NaN
1799,OWZ15803,Phymeg,1.0,0.0,WY,LDERGLNLGVKLKDLTTSATKTLEKFALSAKINKITNNQLATDKSF...,66,182,<UNK>,NaN
1800,Phyinf1_13649,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN
1801,Phyinf1_13658,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN

In [87]:
score = pd.read_csv("../2.Structure_prediction/RXLR_fasta_v3.qc.tsv", sep = "\t")

In [91]:
tree_scores = pd.merge(df, score, on = ["entry", "seq"], how = "inner")

In [96]:
tree_scores[["tree_cluster", "ptm", "plddt"]].groupby("tree_cluster").mean()

                   ptm      plddt
tree_cluster
1.0           0.675075  82.574286
2.0           0.779535  86.785358
3.0           0.802619  88.538061
4.0           0.443437  77.806808

In [98]:
tree_scores[["tree_cluster", "ptm", "plddt"]]

      tree_cluster   ptm      plddt
0              1.0  0.35  60.846312
1              1.0  0.34  64.746667
2              1.0  0.37  59.618971
3              1.0  0.35  53.279765
4              1.0  0.32  50.167303
...            ...   ...        ...
1797           NaN  0.40  58.816842
1798           NaN  0.62  76.204524
1799           NaN  0.55  65.370079
1800           NaN  0.41  63.186393
1801           NaN  0.36  60.636230

[1802 rows x 3 columns]

In [99]:
tree_scores[["tree_cluster", "ptm", "plddt"]].to_csv("../4.WY_tree/tree_scores.txt", sep = "\t")