In [1]:
%cd ../analysis

/var2/Works/junhyeong/RXLR_landscape/analysis

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [2]:
!ls -al

total 120
drwxrwxr-x. 9 junhyeong junhyeong  4096 Jan 28 14:59 .
drwxrwxr-x. 7 junhyeong junhyeong  4096 Dec 17 14:38 ..
drwxrwxr-x. 6 junhyeong junhyeong  4096 Dec 16 16:33 1.RXLR_prediction
drwxrwxr-x. 7 junhyeong junhyeong  4096 Dec 16 20:46 2.Structure_prediction
drwxrwxr-x. 5 junhyeong junhyeong  4096 Jan 20 16:44 3.Clustering
drwxrwxr-x. 4 junhyeong junhyeong  4096 Dec 17 14:37 4.WY_tree
drwxrwxr-x. 2 junhyeong junhyeong  4096 Jan 26 19:18 5.AWR
drwxrwxr-x. 2 junhyeong junhyeong  4096 Jan 28 09:31 6.Update_WY_domain
drwxrwxr-x. 2 junhyeong junhyeong  4096 Jan 28 14:58 .ipynb_checkpoints
-rw-rw-r--. 1 junhyeong junhyeong 74998 Jan 28 14:59 itols.txt
-rw-rw-r--. 1 junhyeong junhyeong   854 Jan 27 13:50 length_bin.tsv
-rw-rw-r--. 1 junhyeong junhyeong   265 Jan 27 12:49 wy_annotation.tsv

In [6]:
import pandas as pd
import colorsys

# Structure cluster

In [28]:
df

,entry,spp,WY,LWY,type,seq,seq_cl,str_cl,PFam,tree_cluster
0,POM75974,Phypal,2.0,0.0,WY,GFERIIQQPIKLNTPGKIDNILGVKKLDELLDPARADALLAKNKLG...,-1,-1,<UNK>,1.0
1,Phyker_46568.831,Phyker,1.0,0.0,WY,GFSLSGLMDKLAAKKLAKAALEDSSKEVQAYRAWEANGHTLDDIKK...,12,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
2,Phyra78544,Phyram,1.0,0.0,WY,GVITNPIRRDMLSSSAYKKEVFDNWLLHNKSSATIRDYLNLNGKRW...,51,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
3,OWZ00140,Phymeg,1.0,0.0,WY,SIIALTKLKTATKKIFDVILKPFKKADHWFMKRLQNDVFERRYRNG...,257,-1,<UNK>,1.0
4,OWZ08332,Phymeg,1.0,0.0,WY,SIVPLKKLKTATKRIFDAISKQFKKAGHWFMKTLREEHYYKKWYRN...,257,-1,<UNK>,1.0
...,...,...,...,...,...,...,...,...,...,...
1797,Phyci1_2936,Phycin,0.0,0.0,no (L)WY,MFSGALPENIASVAKKLPRSKSLPDLRLTVKGKKAVDRLVAQLTRS...,-1,182,<UNK>,NaN
1798,XP_009532894.1,Physoj,1.0,0.0,WY,GIANNPSVAKVLYKLTPNKQKAAEKLFKRLKLGKNTPSIFTNAKFL...,-1,182,<UNK>,NaN
1799,OWZ15803,Phymeg,1.0,0.0,WY,LDERGLNLGVKLKDLTTSATKTLEKFALSAKINKITNNQLATDKSF...,66,182,<UNK>,NaN
1800,Phyinf1_13649,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN
1801,Phyinf1_13658,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN

In [73]:
df = pd.read_csv("./4.WY_tree/RXLR_tree_cluster_by_manual.tsv", sep = "\t")

In [74]:
color_map = {
    1:  "#C84A4A",  # muted red
    2:  "#C8704A",
    3:  "#C89B4A",
    4:  "#B7C84A",
    5:  "#8FC84A",
    6:  "#5FC84A",
    7:  "#4AC87C",
    8:  "#4AC8A8",
    9:  "#4AC8C8",  # muted cyan
    10: "#4A9BC8",
    11: "#4A6FC8",
    12: "#5F4AC8",
    13: "#8F4AC8",
    14: "#B74AC8",
    15: "#C84AA8",
    16: "#C84A7C",
}

In [75]:
df["colors"] = df["str_cl"].map(color_map)

In [76]:
df.dropna(subset = "colors", inplace = True)

In [77]:
df[["entry", "colors", "str_cl"]].to_csv("./itol/structure_cluster.txt", sep = "\t", index = False, header = False)

# Number of WY domain

In [56]:
df = pd.read_csv("./4.WY_tree/RXLR_tree_cluster_by_manual.tsv", sep = "\t")

In [57]:
df.describe()

                WY         LWY       seq_cl       str_cl  tree_cluster
count  1802.000000  1802.00000  1802.000000  1802.000000   1718.000000
mean      1.600999     0.77414    54.372919    24.632630      1.565774
std       1.832539     1.53129    76.796122    37.675407      0.710216
min       0.000000     0.00000    -1.000000    -1.000000      1.000000
25%       0.000000     0.00000     4.000000     3.000000      1.000000
50%       1.000000     0.00000    26.000000    11.000000      1.000000
75%       2.000000     1.00000    70.000000    31.000000      2.000000
max      11.000000     8.00000   423.000000   280.000000      4.000000

In [58]:
color_map = {
    0: "#FFFFFF",
    1: "#DBDBDB",
    2: "#B6B6B6",
    3: "#929292",
    4: "#6D6D6D",
    5: "#494949",
    6: "#242424",
    7: "#000000",
    8: "#000000",
    9: "#000000",
    10: "#000000",
    11: "#000000",
}

In [59]:
df["colors"] = df["WY"].map(color_map)

In [60]:
df.dropna(subset = "colors", inplace = True)

In [61]:
df[["entry", "colors", "WY"]].to_csv("./itol/WY_count.txt", sep = "\t", index = False, header = False)

# TYPE

In [62]:
df = pd.read_csv("./4.WY_tree/RXLR_tree_cluster_by_manual.tsv", sep = "\t")

In [63]:
df

,entry,spp,WY,LWY,type,seq,seq_cl,str_cl,PFam,tree_cluster
0,POM75974,Phypal,2.0,0.0,WY,GFERIIQQPIKLNTPGKIDNILGVKKLDELLDPARADALLAKNKLG...,-1,-1,<UNK>,1.0
1,Phyker_46568.831,Phyker,1.0,0.0,WY,GFSLSGLMDKLAAKKLAKAALEDSSKEVQAYRAWEANGHTLDDIKK...,12,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
2,Phyra78544,Phyram,1.0,0.0,WY,GVITNPIRRDMLSSSAYKKEVFDNWLLHNKSSATIRDYLNLNGKRW...,51,-1,"RXLR phytopathogen effector protein, Avirulenc...",1.0
3,OWZ00140,Phymeg,1.0,0.0,WY,SIIALTKLKTATKKIFDVILKPFKKADHWFMKRLQNDVFERRYRNG...,257,-1,<UNK>,1.0
4,OWZ08332,Phymeg,1.0,0.0,WY,SIVPLKKLKTATKRIFDAISKQFKKAGHWFMKTLREEHYYKKWYRN...,257,-1,<UNK>,1.0
...,...,...,...,...,...,...,...,...,...,...
1797,Phyci1_2936,Phycin,0.0,0.0,no (L)WY,MFSGALPENIASVAKKLPRSKSLPDLRLTVKGKKAVDRLVAQLTRS...,-1,182,<UNK>,NaN
1798,XP_009532894.1,Physoj,1.0,0.0,WY,GIANNPSVAKVLYKLTPNKQKAAEKLFKRLKLGKNTPSIFTNAKFL...,-1,182,<UNK>,NaN
1799,OWZ15803,Phymeg,1.0,0.0,WY,LDERGLNLGVKLKDLTTSATKTLEKFALSAKINKITNNQLATDKSF...,66,182,<UNK>,NaN
1800,Phyinf1_13649,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN
1801,Phyinf1_13658,Phyinf,1.0,0.0,WY,GGTLRIPNQRIRKWLSKDLTPNKVKAKLSISSHTATDSEIYKLYQS...,332,280,<UNK>,NaN

In [69]:
color_map = {
    "WY": "#231651",
    "LWY": "#2374ab",
}

In [70]:
df["colors"] = df["type"].map(color_map)

In [71]:
df.dropna(subset = "colors", inplace = True)

In [72]:
df[["entry", "colors", "type"]].to_csv("./itol/WY_type.txt", sep = "\t", index = False, header = False)